config/routes.rb
Rails.application.routes.draw do
  get 'intertitles/show_all' =>  'intertitles#show_all'
  resources :intertitles
  

  root 'intertitles#index'

end

app/models/intertitle.rb
class Intertitle < ActiveRecord::Base
    validates :title, presence: true
    validates :content, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/intertitles_controller.rb
class IntertitlesController < ApplicationController
  before_action :require_login, except: [:index, :show]

  # GET /intertitles
  # GET /intertitles.json
  def index
    @intertitles = Intertitle.all
    # @intertitles = Intertitle.all.shuffle.take(20)
  end

  # GET /intertitles/1
  # GET /intertitles/1.json
  def show
    @intertitle = Intertitle.find(params[:id])
    @split_intertitle = @intertitle.content.split("\n")
  end

  # GET /intertitles/new
  def new
    @intertitle = Intertitle.new
  end

  # GET /intertitles/1/edit
  def edit
    @intertitle = Intertitle.find(params[:id])
  end

  # POST /intertitles
  # POST /intertitles.json
  def create
    @intertitle = Intertitle.new(intertitle_params)

    respond_to do |format|
      if @intertitle.save
        format.html { redirect_to @intertitle, notice: 'Intertitle was successfully created.' }
        format.json { render :show, status: :created, location: @intertitle }
      else
        format.html { render :new }
        format.json { render json: @intertitle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /intertitles/1
  # PATCH/PUT /intertitles/1.json
  def update
    @intertitle = Intertitle.find(params[:id])
    respond_to do |format|
      if @intertitle.update(intertitle_params)
        format.html { redirect_to @intertitle, notice: 'Intertitle was successfully updated.' }
        format.json { render :show, status: :ok, location: @intertitle }
      else
        format.html { render :edit }
        format.json { render json: @intertitle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /intertitles/1
  # DELETE /intertitles/1.json
  def destroy
    @intertitle = Intertitle.find(params[:id])
    @intertitle.destroy
    respond_to do |format|
      format.html { redirect_to intertitles_url, notice: 'Intertitle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def show_all
    @intertitles = Intertitle.all
  end
  
  # def show_one
  #   @intertitle = Intertitle.find(params[:id])
  # end
  
  
  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def intertitle_params
      params.require(:intertitle).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/intertitles_helper.rb
module IntertitlesHelper
end

app/views/intertitles/_form.html.erb
<div class="form"></div>

<%= form_for(@intertitle) do |f| %>
  <% if @intertitle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@intertitle.errors.count, "error") %> prohibited this intertitle from being saved:</h2>

      <ul>
      <% @intertitle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content, id: 'main_text_area', style: "height: 100px;" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
</div>
<% end %>

<script>
  window.SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;
  const recognition = new SpeechRecognition();
  recognition.interimResults = true;
  recognition.lang = 'en-US';
  const text_area = document.getElementById("main_text_area");

  recognition.addEventListener('result', e => {
    const transcript = Array.from(e.results)
      .map(result => result[0])
      .map(result => result.transcript)
      .join('');
      if (e.results[0].isFinal) {
        text_area.value = text_area.value + transcript + "\n";
        // expand_box_if_needed();
        outer_scroll();
      }
  });
  recognition.addEventListener('end', recognition.start);
  recognition.start();
  
  // function expand_box_if_needed(){
    
  //   if (text_area.scrollHeight > text_area.clientHeight){
  //     console.log("hi expand");
  //     text_area.style.height = text_area.scrollHeight + 'px';
  //   }
    
  // }
  
  function outer_scroll(){
    text_area.scrollTop = text_area.scrollHeight;
    
  }

 
</script>

app/views/intertitles/edit.html.erb
 <div class="form">
    <h1>Editing Intertitle</h1>
    
    <%= render 'form' %>
    
    <%= link_to 'Show', @intertitle %> |
    <%= link_to 'Back', intertitles_path %>
</div>

app/views/intertitles/index.html.erb
<div class="wrapper">
    <!--wrapper-->
    <header class="sticky">
        <nav class="">
        <div id="nav-title">
            <!--header-->
            <h1 id="text">Intertitles</h1>
            <a href="#footer"><h2 id="question">?</h2></a>
            <!--<button onclick="bottomFunction()" id="question" title="Go to top">?</button>-->
        </div>

        </nav>
            <ul id="btn-wrapper">
                <% if signed_in? %>
                   <li class="signout">
                      <%= button_to 'Sign out', sign_out_path, method: :delete %> 
                   </li>
                    <li class="newintertitle">
                        <%= button_to 'Create New intertitle', new_intertitle_path, method: :get %>
                    </li>
                <% end %>
             </ul>
    </header>
    
            
    <section class="main-content">
        <div class="gallery">
            <% @intertitles.each_with_index do |intertitle, index| %>
            
                
                    
                <%= link_to intertitle_path(intertitle), class:"gallery-item" do%>
                    <!--<div class="gallery-item">-->
                    <!--div class="gallery-item font#{(1..5).to_a.sample}"-->
                        <h2 class="title"><%= intertitle.title %></h2>
                        
     
                       
                        <!--<div class="gallery-curtain">-->
                                <!--<%= index %>-->
                                <!-- <%= link_to 'View', intertitle%>-->
                        <!--</div>-->
                       
                                
                <% end %>
            <% end %>
        </div>
        
        
    </section>
    <a name="footer"></a>
    <footer id="footer" >
        <div class="footertextWrapper">
        <h1>Explanation of what Intertitles is and the CRUD interface behind the scene comes here</h1>
        <div class="aside1">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam convallis egestas placerat. Quisque ac faucibus metus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed eu lectus vitae ex consectetur mollis. Maecenas ornare finibus ligula at vehicula. Maecenas auctor a mi a cursus. Vestibulum ex felis, dapibus ac pulvinar sed, venenatis id nisi.

Pellentesque molestie pretium magna, in mattis nisi tristique et. Nulla facilisi. Aliquam dictum lectus libero, ac placerat ex sagittis quis. Donec sit amet libero dapibus, sagittis tellus vitae, varius mauris. Pellentesque imperdiet aliquet magna at facilisis. Donec quis ullamcorper lacus. Morbi sed tortor sem. Nam eu erat sit amet mi lacinia aliquam. Mauris feugiat, nisi eu aliquet gravida, nunc justo mattis nulla, ac ullamcorper sapien velit nec sapien. Proin placerat odio vitae ultricies iaculis. Duis sollicitudin mattis quam viverra maximus. Proin dapibus, leo consequat ultricies efficitur, arcu tellus vehicula ante, id ornare diam metus quis lacus.</p>
        </div>
        <div class="aside2"></div>
        <button onclick="topFunction()" id="myBtn" title="Go to top">&iquest;</button>
        </div>
    </footer>
</div>
 <script>
// generateCanvas();
// function generateCanvas(){

    
//     document.querySelectorAll('canvas').forEach(function(canvas) {
//         var ctx = canvas.getContext('2d');
//         loop(ctx, true);
//     });
// };


// function noise(ctx) {
    
//     var w = ctx.canvas.width,
//         h = ctx.canvas.height,
//         idata = ctx.createImageData(w, h),
//         buffer32 = new Uint32Array(idata.data.buffer),
//         len = buffer32.length,
//         i = 0;

//     for(; i < len;)
//         buffer32[i++] = ((80 * Math.random())|0) << 24;
    
//     ctx.putImageData(idata, 0, 0);
// }

// function loop(ctx, toggle) {
//     toggle = !toggle;
//     if (toggle) {
//         requestAnimationFrame(function() {
//             loop(ctx, !toggle);
//         });
//         return;
//     }
//     noise(ctx);
//     requestAnimationFrame(function() {
//         loop(ctx, !toggle);
//     });
// };

window.onscroll = function() {scrollFunction()};

function scrollFunction() {
  if (document.body.scrollTop > 3000 || document.documentElement.scrollTop > 3000) {
    // document.getElementById("myBtn").classList.remove('top');
    document.getElementById("myBtn").style.display="block";
  } else {
    // document.getElementById("myBtn").classList.add('top');
    
    document.getElementById("myBtn").style.display="";
  }
}

// When the user clicks on the button, scroll to the top of the document
function topFunction() {
//   document.body.scrollTop = 0;
//   document.documentElement.scrollTop = 0;
    window.scroll({
       top:0,
       behavior: 'smooth',
    });
    
}

 </script>

app/views/intertitles/new.html.erb
 <div class="form">
    <h1>New Intertitle</h1>
    
    <%= render 'form' %>
    <%= link_to 'show all', intertitles_show_all_path %>
    <%= link_to 'Back', intertitles_path %>
</div>

app/views/intertitles/show.html.erb
<body class="show"></body>
<section class="intertitle">
  <div class="container"
    <% @split_intertitle.each_with_index do |word, index| %>
        <div class="container" id="intertitle-<%= index %>" style='display: none;'>
            <%= word %>
        </div>
    <% end %>
    <!---->
    <!--<i class="fas fa-volume-up"></i>-->
    <button class="mute volumeToggle"><i class="fas fa-volume-mute"></i></button>
    <button class="unmute invisible volumeToggle"><i class="fas fa-volume-up"></i></button>
  </div>
</section>

<% if signed_in? %>
    <%= link_to 'Edit', edit_intertitle_path, method: :get %>
<% end %>
<%= link_to 'Close X', intertitles_path, style: "color: white; text-decoration: none;"%>
</body>
<script src='https://code.responsivevoice.org/responsivevoice.js'></script>

<script>

//  (function() {
var isMuted = false;
var ids = []
var lineIndex = -1
var muteButton = $('.mute')
var loudButton = $('.unmute')

//$('.container').trigger("click");
responsiveVoice.OnVoiceReady = function (){
    function choseVoice() {
        var voices = ["Australian Female", "Australian Male", "UK English Male", "Uk English Female"];
        var voiceIndex = Math.floor(Math.random() * voices.length);
        return voices[voiceIndex];
    }
    
    function cycle(voice) {
        console.log(lineIndex);
        lineIndex++
        if (lineIndex < ids.length) {
            var text = $(ids[lineIndex]).text().trim();
            $('.intertitle .container').hide();
            if (isMuted == true) {
                $(ids[lineIndex]).fadeIn(500);
            } else {
                responsiveVoice.speak(text, voice);
                 console.log(voice,"this is the voice");
                 
            }
            
            //lineIndex++
            var split_words = text.split(' ');
            //sync voice with text
            var time_to_wait = split_words.length*1000;
            setTimeout(function(){ cycle(voice)},time_to_wait);
            
        } else {
            $('.intertitle').find('.container').hide();
            muteButton.fadeOut(3000);
            loudButton.fadeOut(3000);
        }
    }
    
    $('.intertitle').find('.container').each(function() {
        ids.push('#' + this.id)
    })
    
    cycle(choseVoice());
    
}

$(".volumeToggle").click(function(){
    isMuted = !isMuted
     if (isMuted == true) {
        $(ids[lineIndex]).show(); 
        responsiveVoice.cancel();
        $(".mute").addClass("invisible");
        $(".unmute").removeClass("invisible");
     } else {
         $(ids[lineIndex]).hide();
         $(".mute").removeClass("invisible");
         $(".unmute").addClass("invisible");
         
         
     }
});

// }())
</script>

app/views/intertitles/show_all.html.erb
<p id="notice"><%= notice %></p>
<div class="form">
  <h1>Listing Intertitles</h1>
  
  <table>
    <thead>
      <ul>
        <th>Title</th>
        <th>Content</th>
        <th colspan="3"></th>
      </ul>
    </thead>
  
    <tbody>
      <% @intertitles.each do |intertitle| %>
        <tr>
          <td><%= intertitle.title %></td>
          <td><%= intertitle.content %></td>
          <td><%= link_to 'Show', intertitle, :style => "width:100px;border-radius: 0 !important", :class => "btn btn-success" %></td>
          <td><%= link_to 'Edit', edit_intertitle_path(intertitle), :style => "float:right",:class => "btn btn-info"  %></td>
          <td><%= link_to 'Destroy', intertitle, method: :delete, data: { confirm: 'Are you sure?' },:style => "float:right",:class => "btn btn-danger"  %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <br>
  
  <%= link_to 'New Intertitle', new_intertitle_path %>
  <%= link_to 'Index', intertitles_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Intertitles</title>
  <!--<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">-->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    </div>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>